### ISSUE TITLE
Typo in ibm_is_floating_ip

### ISSUE THREAD

**Issue by bogdandragoiu** [ibm-cloud-docs/ibm-cloud-provider-for-terraform#1]
At the section [ibm_is_floating_ip](https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-vpc-gen2-resources#provider-floating-ip) in VPC infrastructure resources, there is this typo:
```
For more information, see About floatig IP.
                                    ^
```

**Comment by geethasathyamurthy** [comment]
@Bogdandraogoiu, 

Sorry for the delay in response. This is updated, will be published by end of the day in the docs.

Thanks for catching this,
Geetha

**Comment by geethasathyamurthy** [comment]
@bogdandragoiu 

The docs are updated with the finds, https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_floating_ip. Request to close the issue, if you see it is fixed.

Thanks & Regards,
Geetha
