### ISSUE TITLE
404 for endpoint configuration

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/ibm-cloud-provider-for-terraform#10]
https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-config-provider gives 404.

It is linked from the TOC

![image](https://user-images.githubusercontent.com/12746550/116609122-a09e8b00-a8f9-11eb-8106-91651085205f.png)

**Comment by geethasathyamurthy** [comment]
@l2fprod
Request to check this link and confirm is it working now.  

Thanks,
Geetha

**Comment by l2fprod** [comment]
fixed
