### ISSUE TITLE
The default value of disable_public_service_endpoint is false instead of true

### ISSUE THREAD

**Issue by ramonvanstijn** [ibm-cloud-docs/ibm-cloud-provider-for-terraform#2]
Currently we have the input parameter `disable_public_service_endpoint` for resource `ibm_container_vpc_cluster` documented as:

disable_public_service_endpoint - (Optional,Bool) Disable the public service endpoint to prevent public access to the master. Default Value 'true'.

The code, on the master branch, reveals the default is false:
```
			"disable_public_service_endpoint": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
				Description: "Boolean value true if Public service endpoint to be disabled",
```
Docs must be aligned with the code.

**Comment by geethasathyamurthy** [comment]
@ramonvanstijn ,

Thanks for catching this, we have updated the document as per the code in the master branch.

Regards,
Geetha

**Comment by ramonvanstijn** [comment]
Checked the docs and they look good to me, thanks. Closed the issue.
